name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # Cache and install APT Packages
    - name: Cache and Install APT Packages
      uses: awalsh128/cache-apt-pkgs-action@v1.4.3
      with:
        packages: make gcc g++ libasio-dev

    - name: Clone CDFR2026-Program-DriveControl
      run: git clone https://github.com/robotronik/CDFR2026-Program-DriveControl.git ../CDFR2026-Program-DriveControl
    - name: Clone Aruco OpenCV
      run: git clone https://github.com/robotronik/PythonArucoOpenCV.git ../PythonArucoOpenCV
    - name: Clone Arduino
      run: git clone https://github.com/robotronik/cdfr2024-programme-Actionneur ../cdfr2024-programme-Actionneur

    - name: Build and run tests
      run: |
        bash build.sh build
        bash build.sh tests
